# Generated by Django 4.1.4 on 2022-12-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_generator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='serial',
            new_name='id',
        ),
    ]
