# Generated by Django 4.1.4 on 2022-12-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_rename_serial_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='serial',
            field=models.CharField(default='ABC', max_length=16),
        ),
    ]
