# Generated by Django 4.1.4 on 2022-12-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cards.card'),
        ),
    ]
